name: Wolfictl Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      id: lint
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:79e623e83d44d159895da860bc8ae1fed6215f026cd0e9430c2e9292c6790ab3
      with:
        entrypoint: wolfictl
        args: lint
    - name: Enforce YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:79e623e83d44d159895da860bc8ae1fed6215f026cd0e9430c2e9292c6790ab3
      with:
        entrypoint: wolfictl
        args: lint yam
